matrix:
  include:
    # - image: perl:5.22.4-stretch
    # - image: perl:5.36.0-slim-bullseye
    # - image: perl:5.38.0-slim-bookworm
    # - image: perl:5.40.0-slim-bookworm
    # - image: perl:5.42.0-slim-bookworm
    - image: perl:5.43.5-slim-bookworm

steps:
  test:
    when:
      event: [push]
    image: ${image}
    commands:
      - apt-get update -y
      - apt-get install -y gcc 
      - cpanm -n YAML
      - cpanm -n File::Temp
      - cpanm -n Term::ReadLine
      - perl Makefile.PL
      - make
      - make test
